title: "LAST Lab — Latin American SocioTechnical Laboratory for Critical AI"
description: "Laboratorio latinoamericano multinodal de investigación crítica en IA y tecnologías digitales. Origen: UNAJ Investiga e IEAD–USFQ."
theme: jekyll-theme-cayman
